### ISSUE TITLE
Components are automatically injected, hence manual init can be omitted

### ISSUE THREAD

**Issue by AlmasB** [marvinbuff/GalacticCombat#12]
In `BulletComponent`, there is a [line](https://github.com/marvinbuff/GalacticCombat/blob/master/src/main/kotlin/galacticCombat/entities/bullet/BulletComponent.kt#L15):

```
private val projectile: ProjectileComponent by lazy { entity.getComponent(ProjectileComponent::class.java) }
```
that can be replaced with:

```
private lateinit var projectile: ProjectileComponent
```

If a component, c1, has a dependency on another component, c2, and c2 is added before c1 (e.g. in the entity factory), then c2 is injected into c1 during c1 addition. In this case, ProjectileComponent is added before BulletComponent, so injection will happen.

I believe similar `Component` initializations occur in other files, e.g. [PathVertexComponent](https://github.com/marvinbuff/GalacticCombat/blob/master/src/main/kotlin/galacticCombat/entities/path/PathVertexComponent.kt#L11), so they can be updated too. If the component order is not as above in other cases, they can easily be reordered in the factory. The convention is to add built-in components, such as ProjectileComponent, before custom made components because of the dependency order. I think the project already follows this convention, as I can see dependencies via `@Required(ProjectileComponent::class)`.

**Comment by marvinbuff** [comment]
Thank you very much. That is a good tip. I changed it accordingly.
