### ISSUE TITLE
Components should be added inside factory, rather than inside other components

### ISSUE THREAD

**Issue by AlmasB** [marvinbuff/GalacticCombat#4]
Just a suggestion to adhere to the FXGL convention for components, which explicitly shows all components of a given entity type. In some cases this is not possible due to dependencies, but I think, for example, [here](https://github.com/marvinbuff/GalacticCombat/blob/Version0.2/src/main/kotlin/galacticCombat/entities/invader/InvaderComponent.kt#L38) and [here](https://github.com/marvinbuff/GalacticCombat/blob/Version0.2/src/main/kotlin/galacticCombat/entities/bullet/BulletComponent.kt#L20) ProjectileComponent can be added inside a factory.

**Comment by marvinbuff** [comment]
That is reasonable and cleans up the code quite a bit. Thanks for the suggestion.
